services:
  frontend:
    build: ./frontend
    ports:
      - "5357:80" # Map host port 5357 to container port 80 (Nginx)
    depends_on:
      - nginx-proxy # Frontend depends on the Nginx proxy
    environment:
      # Pass the Nginx proxy's internal hostname/port to the frontend for API calls
      REACT_APP_API_BASE_URL: http://nginx-proxy:80

  nodejs-backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      # Example: If your Node.js backend needs to know its own port
      NODE_ENV: development
    # Optionally, specify a custom start command if different from Dockerfile CMD
    # command: node server.js

  flask-backend:
    build: ./flask-backend
    ports:
      - "5001:5001"
    environment:
      # Example: If your Flask backend needs a database URL
      FLASK_ENV: development
    # Optionally, specify a custom start command if different from Dockerfile CMD
    # command: python app.py

  nginx-proxy:
    build: ./nginx
    ports:
      - "80:80" # Map host port 80 to container port 80 (Nginx)
    depends_on:
      - nodejs-backend
      - flask-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount your Nginx config
