services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    environment:
      REACT_APP_NODE_API_URL: http://localhost:5000
      REACT_APP_FLASK_API_URL: http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nodejs-backend:
    build: ./backend/nodeServer
    ports:
      - "5000:5000"  
    environment:
      NODE_ENV: development

  flask-backend:
    build: ./backend/pythonApi
    ports:
      - "5001:5001"  
    environment:
      FLASK_ENV: development